# Form implementation generated from reading ui file 'tes.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Gerenciador de Biblioteca")
        MainWindow.resize(640, 622)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(200, 0))
        self.frame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame.setStyleSheet("background-color: rgb(33, 34, 44);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_2.setMaximumSize(QtCore.QSize(45, 45))
        self.pushButton_2.setStyleSheet("\n"
"QPushButton{\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border:none;\n"
"color: white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(52, 55, 70);\n"
"color:white;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(145, 145, 145);\n"
"}\n"
"\n"
"")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/angle-left.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_3.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_3.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border:none;\n"
"color: white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(52, 55, 70);\n"
"color:white;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(145, 145, 145);\n"
"}\n"
"\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/stats.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_4.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border:none;\n"
"color: white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(52, 55, 70);\n"
"color:white;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(145, 145, 145);\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/add.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_5.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_5.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border:none;\n"
"color: white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(52, 55, 70);\n"
"color:white;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(145, 145, 145);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/graduation-cap.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color: rgb(40, 42, 54);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setStyleSheet("background-color: rgb(52, 55, 70);\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"color: white")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_4)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.page_3)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 20))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideLeft)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_7 = QtWidgets.QFrame(self.tab)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit.setStyleSheet("background-color: rgb(52, 55, 70);\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"color: white")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_6.setMinimumSize(QtCore.QSize(70, 25))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_6.setIcon(icon4)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.verticalLayout_6.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.tab)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_8)
        self.tableWidget.setStyleSheet("border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"background-color: rgb(52, 55, 70);\n"
"color:white;\n"
"")
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setDragDropOverwriteMode(True)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_10.addWidget(self.tableWidget)
        self.frame_13 = QtWidgets.QFrame(self.frame_8)
        self.frame_13.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_13.setMaximumSize(QtCore.QSize(175, 16777215))
        self.frame_13.setStyleSheet("border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButton_24 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_24.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_24.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border:none;\n"
"color: black;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(245, 245, 245);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(236, 236, 236);\n"
"}")
        self.pushButton_24.setObjectName("pushButton_24")
        self.verticalLayout_15.addWidget(self.pushButton_24)
        self.pushButton_21 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_21.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_21.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_15.addWidget(self.pushButton_21)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_12.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_15.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_13.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_15.addWidget(self.pushButton_13)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_15.addItem(spacerItem2)
        self.horizontalLayout_10.addWidget(self.frame_13)
        self.verticalLayout_6.addWidget(self.frame_8)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_9 = QtWidgets.QFrame(self.tab_3)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_9.setStyleSheet("")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_2.setStyleSheet("background-color: rgb(52, 55, 70);\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"color: white")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_6.addWidget(self.lineEdit_2)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_7.setMinimumSize(QtCore.QSize(70, 25))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_7.setIcon(icon4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_6.addWidget(self.pushButton_7)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.tab_3)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.frame_10)
        self.tableWidget_3.setStyleSheet("border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"background-color: rgb(52, 55, 70);\n"
"color:white;")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(40, 42, 54))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_9.addWidget(self.tableWidget_3)
        self.frame_14 = QtWidgets.QFrame(self.frame_10)
        self.frame_14.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_14.setMaximumSize(QtCore.QSize(175, 16777215))
        self.frame_14.setStyleSheet("border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.pushButton_23 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_23.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_23.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border:none;\n"
"color: black;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(245, 245, 245);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(236, 236, 236);\n"
"}")
        self.pushButton_23.setObjectName("pushButton_23")
        self.verticalLayout_16.addWidget(self.pushButton_23)
        self.pushButton_20 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_20.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_20.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_16.addWidget(self.pushButton_20)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_14.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_16.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_15.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_16.addWidget(self.pushButton_15)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_16.addItem(spacerItem3)
        self.horizontalLayout_9.addWidget(self.frame_14)
        self.verticalLayout_7.addWidget(self.frame_10)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_11 = QtWidgets.QFrame(self.tab_2)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_11.setStyleSheet("")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_3.setStyleSheet("background-color: rgb(52, 55, 70);\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"color: white")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_7.addWidget(self.lineEdit_3)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_8.setMinimumSize(QtCore.QSize(70, 25))
        self.pushButton_8.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_8.setIcon(icon4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_7.addWidget(self.pushButton_8)
        self.verticalLayout_8.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.tab_2)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_12)
        self.tableWidget_2.setStyleSheet("border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"background-color: rgb(52, 55, 70);\n"
"color:white;\n"
"")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_8.addWidget(self.tableWidget_2)
        self.frame_15 = QtWidgets.QFrame(self.frame_12)
        self.frame_15.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_15.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame_15.setStyleSheet("border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.pushButton_25 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_25.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_25.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border:none;\n"
"color: black;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(245, 245, 245);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(236, 236, 236);\n"
"}")
        self.pushButton_25.setObjectName("pushButton_25")
        self.verticalLayout_17.addWidget(self.pushButton_25)
        self.pushButton_22 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_22.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_22.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_17.addWidget(self.pushButton_22)
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_16.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_17.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_17.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_17.addWidget(self.pushButton_17)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_17.addItem(spacerItem4)
        self.horizontalLayout_8.addWidget(self.frame_15)
        self.verticalLayout_8.addWidget(self.frame_12)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_4.addWidget(self.tabWidget)
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_13 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(103, 108, 139);\n"
"\n"
"\n"
"\n"
"")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_18.addWidget(self.label_13)
        self.stackedWidget.addWidget(self.page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.page_4)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(0, 20))
        self.tabWidget_2.setDocumentMode(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_16 = QtWidgets.QFrame(self.tab_4)
        self.frame_16.setMaximumSize(QtCore.QSize(600, 16777215))
        self.frame_16.setStyleSheet("")
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_9.addItem(spacerItem5)
        self.label_2 = QtWidgets.QLabel(self.frame_16)
        self.label_2.setStyleSheet("\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border:none;\n"
"color: white")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_4.setStyleSheet("background-color: rgb(52, 55, 70);\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"color: white")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_9.addWidget(self.lineEdit_4)
        self.label_3 = QtWidgets.QLabel(self.frame_16)
        self.label_3.setStyleSheet("\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border:none;\n"
"color: white")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_5.setStyleSheet("background-color: rgb(52, 55, 70);\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"color: white")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_9.addWidget(self.lineEdit_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem6)
        self.horizontalLayout_11.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.tab_4)
        self.frame_17.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_17.setStyleSheet("")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_10.addItem(spacerItem7)
        self.label_4 = QtWidgets.QLabel(self.frame_17)
        self.label_4.setStyleSheet("\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border:none;\n"
"color: white")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.comboBox = QtWidgets.QComboBox(self.frame_17)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox.setStyleSheet("background-color: rgb(52, 55, 70);\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"color: white")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_10.addWidget(self.comboBox)
        self.label_5 = QtWidgets.QLabel(self.frame_17)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_10.addWidget(self.pushButton_9)
        self.pushButton_30 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_30.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_30.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_30.setObjectName("pushButton_30")
        self.verticalLayout_10.addWidget(self.pushButton_30)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_10.addItem(spacerItem8)
        self.horizontalLayout_11.addWidget(self.frame_17)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_18 = QtWidgets.QFrame(self.tab_5)
        self.frame_18.setMaximumSize(QtCore.QSize(600, 16777215))
        self.frame_18.setStyleSheet("")
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_11.addItem(spacerItem9)
        self.label_6 = QtWidgets.QLabel(self.frame_18)
        self.label_6.setStyleSheet("\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border:none;\n"
"color: white")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_11.addWidget(self.label_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_18)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_6.setStyleSheet("background-color: rgb(52, 55, 70);\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"color: white")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_11.addWidget(self.lineEdit_6)
        self.label_7 = QtWidgets.QLabel(self.frame_18)
        self.label_7.setStyleSheet("\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border:none;\n"
"color: white")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_18)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_7.setStyleSheet("background-color: rgb(52, 55, 70);\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"color: white")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_11.addWidget(self.lineEdit_7)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_11.addItem(spacerItem10)
        self.horizontalLayout_12.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.tab_5)
        self.frame_19.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_19.setStyleSheet("")
        self.frame_19.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_12.addItem(spacerItem11)
        self.label_8 = QtWidgets.QLabel(self.frame_19)
        self.label_8.setStyleSheet("\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border:none;\n"
"color: white")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_12.addWidget(self.label_8)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_19)
        self.comboBox_2.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_2.setStyleSheet("background-color: rgb(52, 55, 70);\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"color: white")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_12.addWidget(self.comboBox_2)
        self.label_9 = QtWidgets.QLabel(self.frame_19)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_12.addWidget(self.label_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_19)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_12.addWidget(self.pushButton_10)
        self.pushButton_29 = QtWidgets.QPushButton(self.frame_19)
        self.pushButton_29.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_29.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_29.setObjectName("pushButton_29")
        self.verticalLayout_12.addWidget(self.pushButton_29)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem12)
        self.horizontalLayout_12.addWidget(self.frame_19)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.tab_6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_20 = QtWidgets.QFrame(self.tab_6)
        self.frame_20.setMaximumSize(QtCore.QSize(600, 16777215))
        self.frame_20.setStyleSheet("")
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_13.addItem(spacerItem13)
        self.label_10 = QtWidgets.QLabel(self.frame_20)
        self.label_10.setStyleSheet("\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border:none;\n"
"color: white")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_13.addWidget(self.label_10)
        self.frame_22 = QtWidgets.QFrame(self.frame_20)
        self.frame_22.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_22.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.frame_22)
        self.label_14.setMinimumSize(QtCore.QSize(0, 25))
        self.label_14.setStyleSheet("background-color: rgb(52, 55, 70);\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border:none;\n"
"color: white;\n"
"\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.pushButton_26 = QtWidgets.QPushButton(self.frame_22)
        self.pushButton_26.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_26.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_26.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_14.addWidget(self.pushButton_26)
        self.verticalLayout_13.addWidget(self.frame_22)
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_18.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_18.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_13.addWidget(self.pushButton_18)
        self.label_11 = QtWidgets.QLabel(self.frame_20)
        self.label_11.setStyleSheet("\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border:none;\n"
"color: white")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_13.addWidget(self.label_11)
        self.frame_23 = QtWidgets.QFrame(self.frame_20)
        self.frame_23.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_23.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.frame_23)
        self.label_15.setMinimumSize(QtCore.QSize(0, 25))
        self.label_15.setStyleSheet("background-color: rgb(52, 55, 70);\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border:none;\n"
"color: white;\n"
"\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.pushButton_27 = QtWidgets.QPushButton(self.frame_23)
        self.pushButton_27.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_27.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_27.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_15.addWidget(self.pushButton_27)
        self.verticalLayout_13.addWidget(self.frame_23)
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_19.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_19.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_13.addWidget(self.pushButton_19)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_13.addItem(spacerItem14)
        self.horizontalLayout_13.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.tab_6)
        self.frame_21.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_21.setStyleSheet("")
        self.frame_21.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_14.setSpacing(4)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_14.addItem(spacerItem15)
        self.label_12 = QtWidgets.QLabel(self.frame_21)
        self.label_12.setStyleSheet("\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border:none;\n"
"color: white")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_14.addWidget(self.label_12)
        self.spinBox = QtWidgets.QSpinBox(self.frame_21)
        self.spinBox.setMinimumSize(QtCore.QSize(0, 25))
        self.spinBox.setStyleSheet("background-color: rgb(52, 55, 70);\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"color: white")
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_14.addWidget(self.spinBox)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_21)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_14.addWidget(self.pushButton_11)
        self.pushButton_28 = QtWidgets.QPushButton(self.frame_21)
        self.pushButton_28.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_28.setStyleSheet("QPushButton{\n"
"background-color: rgb(52, 55, 70);\n"
"border:none;\n"
"color: white;\n"
"font: 63 8pt \"Open Sans Semibold\";\n"
"border: 1px solid rgb(30, 30, 30);\n"
"border-radius:2px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(60, 64, 81);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 34, 44);\n"
"}")
        self.pushButton_28.setObjectName("pushButton_28")
        self.verticalLayout_14.addWidget(self.pushButton_28)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_14.addItem(spacerItem16)
        self.horizontalLayout_13.addWidget(self.frame_21)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.verticalLayout_5.addWidget(self.tabWidget_2)
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", " Gerenciar"))
        self.pushButton_4.setText(_translate("MainWindow", " Cadastrar"))
        self.pushButton_5.setText(_translate("MainWindow", " Sobre       "))
        self.pushButton.setText(_translate("MainWindow", "X"))
        self.pushButton_6.setText(_translate("MainWindow", "Buscar"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CPF"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ano/Série/Curso"))
        self.pushButton_24.setText(_translate("MainWindow", "Selecionar"))
        self.pushButton_21.setText(_translate("MainWindow", "Atualizar"))
        self.pushButton_12.setText(_translate("MainWindow", "Editar"))
        self.pushButton_13.setText(_translate("MainWindow", "Excluir"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Aluno"))
        self.pushButton_7.setText(_translate("MainWindow", "Buscar"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Livro"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ISBN"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Categoria"))
        self.pushButton_23.setText(_translate("MainWindow", "Selecionar"))
        self.pushButton_20.setText(_translate("MainWindow", "Atualizar"))
        self.pushButton_14.setText(_translate("MainWindow", "Editar"))
        self.pushButton_15.setText(_translate("MainWindow", "Excluir"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Livro"))
        self.pushButton_8.setText(_translate("MainWindow", "Buscar"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Livro"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Dias"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Data de Entrega"))
        self.pushButton_25.setText(_translate("MainWindow", "Selecionar"))
        self.pushButton_22.setText(_translate("MainWindow", "Atualizar"))
        self.pushButton_16.setText(_translate("MainWindow", "Editar"))
        self.pushButton_17.setText(_translate("MainWindow", "Excluir"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Aluguel"))
        self.label_13.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"justify\">Dário Romão</p><p align=\"justify\">Esdras Gabriel</p><p align=\"justify\">Flávio Gabriel</p><p align=\"justify\">Guilherme Gabriel</p><p align=\"justify\">Matheus Emanuel</p><p align=\"justify\">Renato Ferreira</p><p align=\"justify\">Wenderson Juvenal</p><p align=\"justify\"><br/></p><p align=\"justify\"><br/></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Dário Romão</p><p align=\"center\">Esdras Gabriel</p><p align=\"center\">Flávio Gabriel</p><p align=\"center\">Guilherme Gabriel</p><p align=\"center\">Matheus Emanuel</p><p align=\"center\">Renato Ferreira</p><p align=\"center\">Wenderson Juvenal</p><p align=\"center\">3°A D.S.</p><p align=\"center\"><br/></p><p align=\"center\"><br/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Nome"))
        self.label_3.setText(_translate("MainWindow", "CPF"))
        self.label_4.setText(_translate("MainWindow", "Ano/Série/Curso"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1°A D.S"))
        self.comboBox.setItemText(1, _translate("MainWindow", "1°B D.S"))
        self.comboBox.setItemText(2, _translate("MainWindow", "1°A ADM"))
        self.comboBox.setItemText(3, _translate("MainWindow", "1°B ADM"))
        self.comboBox.setItemText(4, _translate("MainWindow", "2°A D.S"))
        self.comboBox.setItemText(5, _translate("MainWindow", "2°B D.S"))
        self.comboBox.setItemText(6, _translate("MainWindow", "2°A ADM"))
        self.comboBox.setItemText(7, _translate("MainWindow", "2°B ADM"))
        self.comboBox.setItemText(8, _translate("MainWindow", "3°A D.S"))
        self.comboBox.setItemText(9, _translate("MainWindow", "3°B D.S"))
        self.comboBox.setItemText(10, _translate("MainWindow", "3°A ADM"))
        self.comboBox.setItemText(11, _translate("MainWindow", "3°B ADM"))
        self.pushButton_9.setText(_translate("MainWindow", "Cadastrar"))
        self.pushButton_30.setText(_translate("MainWindow", "Editar"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Aluno"))
        self.label_6.setText(_translate("MainWindow", "Nome do Livro"))
        self.label_7.setText(_translate("MainWindow", "ISBN"))
        self.label_8.setText(_translate("MainWindow", "Categoria"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Romance"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Drama"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Tecnico"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Histórico"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Fantasia"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Ficção Científica"))
        self.pushButton_10.setText(_translate("MainWindow", "Cadastrar"))
        self.pushButton_29.setText(_translate("MainWindow", "Editar"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Livro"))
        self.label_10.setText(_translate("MainWindow", "Aluno"))
        self.pushButton_26.setText(_translate("MainWindow", "X"))
        self.pushButton_18.setText(_translate("MainWindow", "Selecionar"))
        self.label_11.setText(_translate("MainWindow", "Livro"))
        self.pushButton_27.setText(_translate("MainWindow", "X"))
        self.pushButton_19.setText(_translate("MainWindow", "Selecionar"))
        self.label_12.setText(_translate("MainWindow", "Dias de aluguel"))
        self.pushButton_11.setText(_translate("MainWindow", "Cadastrar"))
        self.pushButton_28.setText(_translate("MainWindow", "Editar"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Aluguel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
